services:
  db:
    image: postgres:17
    container_name: sport-class-booking-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: sport_class_booking_db
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-qwerty}

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d sport_class_booking_db"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata: