spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/sport_class_booking_db
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:qwerty}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_URL:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:qwerty}


security:
  jwt:
    secret: ${JWT_SECRET:very-very-secret-key-min-256-bytes-required}
    expiration: ${JWT_EXPIRATION_MILLIS:1800000}
  refresh:
    expiration: ${REFRESH_EXPIRATION_MILLIS:2629746000}
  bcrypt:
    rounds: ${BCRYPT_ROUNDS:10}

logging:
  level:
    org:
      springframework:
        security: ERROR