server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: sport-class-booking-backend

  liquibase:
    change-log: classpath:db/changelog/master.xml

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
